//
// Created by raven on 6/11/20.
//

#ifndef PHONEMIRROR_EVENTS_H
#define PHONEMIRROR_EVENTS_H

#define EVENT_NEW_SESSION SDL_USEREVENT
#define EVENT_NEW_FRAME (SDL_USEREVENT + 1)
#define EVENT_DECODER_STOPPED (SDL_USEREVENT + 2)

#endif //PHONEMIRROR_EVENTS_H
